### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by AlphaGamerHere** [offyerrocker/PD2-ClosedCaptions#2]
Application has crashed: C++ exception
mods/Closed Captions/lua/menumanager.lua:1159: attempt to concatenate a nil value

SCRIPT STACK

func() @mods/Closed Captions/lua/menumanager.lua:1534
post_event() @mods/base/req/core/Hooks.lua:268
complete_rearming() lib/units/equipment/sentry_gun/sentrygunmovement.lua:131
_updator() lib/units/equipment/sentry_gun/sentrygunmovement.lua:119
lib/units/equipment/sentry_gun/sentrygunmovement.lua:64

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.107.25
	CPU : Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1660 Ti / nvldumd.dll[27.21.14.6192]
	Language : english
	Memory :     16302MB 472KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek High Definition Audio))

**Comment by offyerrocker** [comment]
Thanks for your report. I've just uploaded a new version to address this issue- please try it and see if it solves the problem.
